### ISSUE TITLE
Portfolio: Details Popup Optimization

### ISSUE THREAD

**Issue by ZikaZaki** [yasinabdmahmood/portfolio-website#12]
Hi, **@yasinabdmahmood**. You have done great so far, but you could still improve your code:
- [x] You could add a `blur` function to blur the background content when the popup window opens.
- [x] You could make your `JavaScript` code more dynamic by reusing the `card-works` elements previously used in your `html` code.

**Comment by GraceAbike** [comment]
![StandingOvationGIF](https://user-images.githubusercontent.com/88346506/181444285-2eb10f50-8ccb-422c-96a0-86e9ef42f5c4.gif)

-  Excellent job 💯 
- No linter error ✔️
- Good explanation ✔️

**Comment by benardop** [comment]
Good work @yasinabdmahmood 👍 
- I would suggest you please try and find a way to break the cases of a long line of code in the JavaScript file into short lines for
 better readability.
